### ISSUE TITLE
Is any support exist on uberPay wallet!?

### ISSUE THREAD

**Issue by cryptomate** [UberPay/uberpay-wallet#19]
hi.
in uberpay wallet no link to support site,
also can't foud any web support ,no any contact info such as real address, phone etc..
my transfers to uber wallet, lost somewhere, in wallet balance zero!
so,  were I can get support?!

**Comment by geopayme** [comment]
if you look at your Google Play store or UberPay.io which ever you can reach online, try send your request to support@geopay.me its all on both sides. That includes twitter. You have not tried hard enough to find support, only unfounded complains for both UberPay and Coinomi! So try harder next time!

https://geopaymeinc.freshdesk.com/support/login
