### ISSUE TITLE
CLAM coins not come to wallet, no support

### ISSUE THREAD

**Issue by cryptomate** [UberPay/uberpay-wallet#20]
My transfers to uber wallet, lost somewhere, in wallet balance zero!
it is about Clams.
all transactions regestered and you can check it yourself.
My uberpay wallets:
xSmCn25gpVyXprQrbt5DkkJPQQXv8FLKhB
http://khashier.com/address/xSmCn25gpVyXprQrbt5DkkJPQQXv8FLKhB
xGCDctXFyLovdPxAN6KVMgqCwVhKxQtvGz
http://khashier.com/address/xGCDctXFyLovdPxAN6KVMgqCwVhKxQtvGz
On Clam site yo can see multiple transactions but nothing
Comes to wallet in wallet balance is 0!
I sent also two times from my coinomi wallet to uber
Nothing comes!
Sent to
xSmCn25gpVyXprQrbt5DkkJPQQXv8FLKhB
Id
7937b4994d0c1ba4ce5709711711d97aac6bf246d7abd56f8f01e7aa90a5f1fb
Sent to
xGCDctXFyLovdPxAN6KVMgqCwVhKxQtvGz
I'd
4cb9cadd234f82750cfa36d00433041fffe51ed893f91e35bde2b97d96abbbd9
Also shadow coins never comes in wallet there always "no connection"
l tested your wallet use small amounts of different coins.
so fare another coins comes fine.
l hopes, to use uber wallet for future serious amounts, but because lack of support and needed options, unclear instructions,usage difficulty,undelivered funds, future usage of this product for me, questionable.
l hope you will be able to make wallet usable in some time.
best regards,
Walter.

**Comment by geopayme** [comment]
I have reviewed the Clams issue and the Clam Team has made changed to the electrum server that only UberPay was affected. Even though we try to maintain a good relationship with everyone, some folks still try to create issues. Many new changes are on the way for UberPay including the removal of ShapeShift and the inclusion of our own exchange (http://doecoins.com) still beta site. You have to understand that all electrum servers are run by the coin communities and some by coinomi, that is a major issue on reliability, on coins that we have help communities maintain and support their electrum servers, there never have been issues. That is the ideological difference between UberPay and Coinomi, they are both good wallets but serve a different vision!

**Comment by cryptomate** [comment]
Thank you for response.
I checked my uberpay again several times on two different smartphones ( kyocera and zte).
But no any difference, wallet can't see my transfers!
I'm recover walless but no result.
But my coinomi Wallet work with Clam just fine!
So I got idea to use recovery phase from uuberpay wallet on my coinomi ,in hope it will create same wallet for clame. So I did it...
And what do you think?....
IT IS WORK!!!
coinomi wallet accept phrase I use in uberpay and now I can see all my lost transactions in coinomi wallet! But not in uber wallet....
So it show, that iissue is in uberpay..
and it is not resolved yet....
actually there second issue -shadow coins not work it shows all the time " no connection" but in coinomi is same...no idea why....

About support...it must be clearly indicated in application as in new version of coinomi.

thanks agIn for responce.

**Comment by cryptomate** [comment]
so, i waited a week and check again, send few transactions, cheked in on chain
all registered, but wallet can,t see clams....
I rechecked on 3 different smartphones.
it is not fauset problem because I send myself..
and I send not oly clams but dozen another's currency. and all work fine exept clams and shadow.
If anybody can help with this,I appreciate it....

**Comment by geopayme** [comment]
Yes, an issue exist with CLAM thank for your notice! 

As far as ShadowCash, you need to contact the shadowcash development team to see why their electrum servers do no run?

Most servers that are run on UberPay and Coinomi are community supported and some are run by Coinomi, so if a server is not active, you can only blame the coin developers that have neglected to continue support for their coin. All coins in UberPay after the next release will have a server monitor, and if any of the servers are not actively running the coins will be removed from UberPay.

Below is the ShadowCash Electrum Server that we monitor

Host    Port    Proto   UTXO Root   Height  Blocktime   Version Connection  ConnectionTime  Status  Uptime Hour Day Month
104.47.160.204  5026    tcp     0           closed  2016-03-30 06:30:33 CLOSED  0.0000 0.0000 0.0000

**Comment by cryptomate** [comment]
Tank you for respone. I checked link and you right, looks like shadows out...but in many traders sites shadow still appear as live...strange...
looks like you monitoring this site,so you are really care about uberpay, I read all comments and can see that you really upset about my review.
l did not mean to insulting nobody, it was just my opinion. lt is all complicated for me, l have lots of questions abou uberpay wallet and can't found answers...
Anyway,after I read all you posts, it seems for me you are good man and l hope upgraded new version will be goood and l will make good review.

I don't want to open new issue and if you happens to read this post, and have minute to answer my question, please explane how I can extract keys from uberpay? Is any tool exist?
now I use toos from coinomi site but there not all currency as in wallet ,only few.
it will be really nice if in new version, will be tool like in
Jaxx wallet, and imbedded tool fo create paper wallet.
Now I use separate applications for create QR code  and for keys extract, really uncomfortable...
also, currencies in wallet not same as on shapeshift,it will be grate to have all shapeshift coins in wallet plus anotherss..:)
 Thank you in advance Sir.
Best regards.

**Comment by geopayme** [comment]
Please send any support issues to support@geopay.me so we can track any requests. Github is not a support site but a development platform. Unfortunately people post here and in many cases time goes bye with a late response! 

Thank you!
