### ISSUE TITLE
CoinSwap transaction on uberpay pending more than 10 hrs

### ISSUE THREAD

**Issue by alokin1975** [UberPay/uberpay-wallet#21]
Yesterday I  made  coinswap  BTC to altcoins in my uberpay pay wallet.
Here is one of my 3 my transaction Id: 7aae6227bde956ffad2917167701a3cbb758c759b9541048c87d476809df026c

More than 10 hrs transaction status is : waiting for transaction confirmation.
I can see transactions on BTC and all is in same status.

Where is the problem?
Can you help me?

Regards.

**Comment by geopayme** [comment]
can you send an email to support@geopay.me, easier to handle the support there!

**Comment by geopayme** [comment]
It seems the transaction you posted has cleared and is confirmed!
