### ISSUE TITLE
Gulden

### ISSUE THREAD

**Issue by mjmacleod** [UberPay/uberpay-wallet#6]
Please feel free to add support for Gulden https://gulden.com if you want - everything you need should be available in our Coinomi pull request - https://github.com/Coinomi/coinomi-android/pull/84

**Comment by geopayme** [comment]
Done already... I know you declared 2 servers, but I take it you are waiting for some to deploy them...
Maybe the Gulden dev community! I am monitoring your server and I see its running well.

Electrum server: electrum2.gulden.com:5038:tcp - OK
Server block height: 327063
Current block height: 327063
